# Generated by Django 5.0.2 on 2024-03-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
