# Generated by Django 5.0.2 on 2024-03-03 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 0, 35, 32, 800726)),
        ),
        migrations.AddField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 0, 35, 32, 800726)),
        ),
    ]
