# Generated by Django 5.0.2 on 2024-03-03 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_customer_created_at_quote_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 17, 36, 58, 673382)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 17, 36, 58, 673382)),
        ),
    ]
