# Generated by Django 5.0.2 on 2024-03-03 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_customer_created_at_alter_quote_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TypeformResponse',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('form_id', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.customer')),
            ],
        ),
    ]
