# Generated by Django 5.0.2 on 2024-03-03 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_typeformresponse_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeformresponse',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='client.customer'),
        ),
    ]
