# Generated by Django 5.0.2 on 2024-03-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_typeformresponse_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFormResponse',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('submit_at', models.DateTimeField()),
                ('customer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='client.customer')),
            ],
        ),
    ]
